import JSZip from 'jszip';
import centerOfMass from '@turf/center-of-mass';
import uniq from 'lodash.uniq';
import { poiClassAndSubclass } from './poi';

const unitCategoryToOsm = {
  brick: 'column',
  column: 'column',
  concrete: 'column',
  structure: 'column',
  unenclosedarea: 'area',
  walkway: 'corridor',
};

const occupantCategoryToOsm = {
  '3dprinting': { shop: '3d_printing' },
  'acai': { amenity: 'fast_food', cuisine: 'açaí' },
  'accessories': { shop: 'accessories' },
  'accounting': { office: 'accountant' },
  'acnetreatment': { 'healthcare': 'dermatologist', 'healthcare:speciality': 'acne' },
  'acupuncture': { healthcare: 'alternative', 'healthcare:speciality': 'acupuncture'},
  'adoptionservices': { office: 'adoption_agency' },
  'adulteducation': null,
  'adultentertainment': { amenity: 'stripclub' },
  'adultstore': { shop: 'erotic' },
  'advertising': null,
  'advisoryservices': null,
  'afghani':  { amenity: 'restaurant', cuisine: 'afghan' },
  'african':  { amenity: 'restaurant', cuisine: 'african' },
  'agritourism': null,
  'airfield': null,
  'airline': null,
  'airport.regional': { aeroway: 'aerodrome', 'aerodrome:type': 'regional'},
  'airportloungebar': null,
  'airportshuttle': null,
  'airsoft': { leisure: 'pitch', sport: 'airsoft'},
  'allergies': null,
  'alternativemedicine': null,
  'american.modern': { amenity: 'restaurant', cuisine: 'american' },
  'amusementpark': null,
  'amusementpark.ride': null,
  'animalshelter': null,
  'antiques': { shop: 'antiques'},
  'apmstop': null,
  'appliances': { shop: 'appliance'},
  'arabian': { amenity: 'restaurant', cuisine: 'arabian' },
  'arabian.pizza': { amenity: 'restaurant', cuisine: 'arabian;pizza' },
  'arcade': { leisure: 'amusement_arcade' },
  'archery': { leisure: 'pitch', sport: 'archery' },
  'architecture': { office: 'architect' },
  'argentine': { amenity: 'restaurant', cuisine: 'argentinian' },
  'armenian': { amenity: 'restaurant', cuisine: 'armenian' },
  'artgallery': { shop: 'art' }
  'artinstruction': null,
  'arts.entertainment': null,
  'artsandcrafts': null,
  'artschool': null,
  'artstudio': null,
  'artstudio.rental': null,
  'artsupplies': null,
  'asianfusion': { amenity: 'restaurant', cuisine: 'asian_fusion' },
  'astrologist': null,
  'asturian': { amenity: 'restaurant', cuisine: 'asturian' },
  'atm': { amenity: 'atm' },
  'atm.cryptocurrency': null,
  'audiovideoequipment': null,
  'auditory': null,
  'australian': { amenity: 'restaurant', cuisine: 'australian' },
  'australian.modern': { amenity: 'restaurant', cuisine: 'australian' },
  'austrian': { amenity: 'restaurant', cuisine: 'austrian' },
  'austrian.schnitzel': { amenity: 'restaurant', cuisine: 'austrian;schnitzel' },
  'auto.accessibilityequipment': null,
  'auto.bodyshop': null,
  'auto.carbuyer': null,
  'auto.carshare': null,
  'auto.carwash': null,
  'auto.dealer.boat': null,
  'auto.dealer.car': null,
  'auto.dealer.motorcycle': null,
  'auto.dealer.rv': null,
  'auto.dentrepair.mobile': null,
  'auto.detailing': null,
  'auto.electric': null,
  'auto.evcharge': null,
  'auto.evcharge.dcfast': null,
  'auto.evcharge.tesla': null,
  'auto.glass': null,
  'auto.oilchange': null,
  'auto.parts': null,
  'auto.repair': null,
  'auto.repair.transmission': null,
  'auto.repair.wheelrim': null,
  'auto.repair.windshield': null,
  'auto.servicestation': null,
  'auto.shipping': null,
  'auto.stereoinstallation': null,
  'auto.tires': null,
  'auto.upholstery': null,
  'automotive': null,
  'autopartssupplies': null,
  'babyclothesandsupplies': null,
  'bagels': { amenity: 'cafe', cuisine: 'bagel' },
  'bakedgoods': { shop: 'bakery' },
  'ballonservices': null,
  'bangladeshi': { amenity: 'restaurant', cuisine: 'bagladeshi' },
  'bank': { amenity: 'bank' },
  'bar': { amenity: 'bar' },
  'barbecue': { amenity: 'restaurant', cuisine: 'barbecue' },
  'barber': null,
  'barfood': null,
  'barreclass': null,
  'baseballfield': null,
  'bathingarea': null,
  'batteries': null,
  'battingcages': null,
  'beach': null,
  'beautysalon': null,
  'beautyspas': null,
  'bedbreakfast': null,
  'beerbar': null,
  'beergarden': null,
  'beerhall': null,
  'beerwineandspirits': null,
  'beerwinespirits': null,
  'beisl': { amenity: 'restaurant', cuisine: 'austrian;beisl',
  'belgian': { amenity: 'restaurant', cuisine: 'belgian' },
  'belgian.flemish': { amenity: 'restaurant', cuisine: 'flemish' },
  'bengali': { amenity: 'restaurant', cuisine: 'bengali' },
  'beveragestore': { shop: 'beverages'},
  'bicycle.repair': null,
  'bicyclerental': null,
  'bicycleshop': null,
  'bikesandequipment': null,
  'billingservices': null,
  'bingo': null,
  'biryani': { amenity: 'restaurant', cuisine: 'biryani'},
  'bistro': { amenity: 'café', fixme: 'bistro'},
  'blacksea': { amenity: 'restaurant', cuisine: 'black_sea' },
  'blinds': null,
  'blooddonation': null,
  'blooddonationcenter': null,
  'bodycontouring': null,
  'bodypiercing': null,
  'books': null,
  'booksmagazinesmusicvideo': null,
  'botanicalgarden': null,
  'bowlingalley': null,
  'boxing': null,
  'brazilian': { amenity: 'restaurant', cuisine: 'brazilian' },
  'brazilian.centralbrazil': { amenity: 'restaurant', cuisine: 'brazilian;central_brazil' },
  'brazilian.empanadas': { amenity: 'restaurant', cuisine: 'brazilian;empanada' },
  'brazilian.northeasternbrazil': { amenity: 'restaurant', cuisine: 'brazilian;northeastern_brazil' },
  'brazilian.northernbrazil': { amenity: 'restaurant', cuisine: 'brazilian;northern_brazil' },
  'breakfastandbrunch': { amenity: 'restaurant', cuisine: 'breakfast;brunch' },
  'brewery': null,
  'brewpub': null,
  'bridalstore': null,
  'british': { amenity: 'restaurant', cuisine: 'british' },
  'bubbletea': { amenity: 'cafe', cuisine: 'bubble_tea' },
  'buffet': { amenity: 'restaurant', cuisine: 'buffet' },
  'buildingsupplies': null,
  'bulgarian': { amenity: 'restaurant', cuisine: 'bulgarian' },
  'bulkmedicalbilling': null,
  'bungeejumping': null,
  'burgers': { amenity: 'restaurant', cuisine: 'burger' },
  'burmese': { amenity: 'restaurant', cuisine: 'burmese' },
  'businesscampus': null,
  'businessconsulting': null,
  'busrental': null,
  'busstop': null,
  'butcher': { shop: 'butcher' },
  'cabinets': null,
  'cafe': { amenity: 'cafe' },
  'cafeteria': { amenity: 'fast_food', 'fast_food': 'cafeteria' },
  'cajun': { amenity: 'restaurant', cuisine: 'cajun' },
  'cakes': null,
  'calligraphy': null,
  'cambodian': { amenity: 'restaurant', cuisine: 'cambodian' },
  'canadian.modern': { amenity: 'restaurant', cuisine: 'canadian' },
  'candy': null,
  'candy.dagashi': null,
  'cannabisdispensary': null,
  'canteen': { amenity: 'canteen'},
  'cardioclasses': null,
  'cardiology': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'cardiology' },
  'cards.stationery': null,
  'careercounseling': null,
  'caribbean': null,
  'caricaturist': null,
  'carouselride': null,
  'carpet': null,
  'carrental': { amenity: 'car_rental' },
  'catering': null,
  'cellphoneaccessories': null,
  'challengecourse': null,
  'champagnebar': null,
  'cheese': { shop: 'cheese' },
  'cheesesteaks': { restaurant: 'fast_food', cuisine: 'cheesesteak' },
  'chickenshop': { amenity: 'restaurant', cuisine: 'chicken' },
  'chickenwings': { amenity: 'restaurant', cuisine: 'wings' },
  'childbirthschool': null,
  'childcare': null,
  'chilean': { amenity: 'restaurant', cuisine: 'chilean' },
  'chimneycakes': null,
  'chinese': { amenity: 'restaurant', cuisine: 'chinese' },
  'chinese.cantonese': { amenity: 'restaurant', cuisine: 'chinese;cantonese' },
  'chinese.dimsum': { amenity: 'restaurant', cuisine: 'chinese;dimsum' },
  'chinese.fuzhou': { amenity: 'restaurant', cuisine: 'chinese;fuzhou' },
  'chinese.hainan': { amenity: 'restaurant', cuisine: 'chinese;hainan' },
  'chinese.hakka': { amenity: 'restaurant', cuisine: 'chinese;hakka' },
  'chinese.henghwa': { amenity: 'restaurant', cuisine: 'chinese;henghwa' },
  'chinese.hokkien': { amenity: 'restaurant', cuisine: 'chinese;hokkien' },
  'chinese.hunan': { amenity: 'restaurant', cuisine: 'chinese;hunan' },
  'chinese.pekinese': { amenity: 'restaurant', cuisine: 'chinese;pekinese' },
  'chinese.shanghainese': { amenity: 'restaurant', cuisine: 'chinese;shanghainese' },
  'chinese.szechuan': { amenity: 'restaurant', cuisine: 'chinese;szechuan' },
  'chinese.teochew': { amenity: 'restaurant', cuisine: 'chinese;teochew' },
  'chinesebazaar': null,
  'chiropractic': { healthcare: 'alternative', 'healthcare:speciality': 'chiropractic'},
  'chocolate': null,
  'christmastrees': null,
  'churros': null,
  'cider': null,
  'cigarbar': null,
  'cinema': null,
  'cityhall': null,
  'climbing': null,
  'clinic': null,
  'clockrepair': null,
  'clothing': { shop: 'clothes' },
  'clothing.bespoke': { shop: 'clothes' },
  'clothing.childrens': { shop: 'clothes' },
  'clothing.mens': { shop: 'clothes' },
  'clothing.plussize': { shop: 'clothes' },
  'clothing.womens': { shop: 'clothes' },
  'cocktailbar': null,
  'coffee': { shop: 'coffee' },
  'coffee.tea': { shop: 'coffee' },
  'coffeeroaster': null,
  'coffeeteasupplies': null,
  'coincashingkiosk': null,
  'college': null,
  'colombian': { amenity: 'restaurant', cuisine: 'colombian' },
  'comedyclub': null,
  'comfortfood': { amenity: 'restaurant', cuisine: 'comfortfood' },
  'comicbooks': null,
  'commercialrealestate': null,
  'commissionedartists': null,
  'communitybookbox': null,
  'communitycenter': null,
  'computersandaccessories': null,
  'conceptshop': null,
  'concourse': null,
  'condominium': null,
  'congee': { amenity: 'restaurant', cuisine: 'congee' },
  'constructionequipmentrental': null,
  'contractors': null,
  'conveniencestore': { shop: 'convenience' },
  'conveyorsushi': { amenity: 'restaurant', cuisine: 'conveyorsushi' },
  'cooking.instruction': null,
  'cookingschool': null,
  'copyshop': { shop: 'copyshop' },
  'corporateheadquarters': null,
  'corporateoffices': null,
  'corsican': { amenity: 'restaurant', cuisine: 'corsican' },
  'cosmetics': null,
  'cosmeticsurgery': null,
  'cosmetologyschool': null,
  'costumes': null,
  'countertopinstallation': null,
  'countryclub': null,
  'courier': null,
  'crepes': { amenity: 'fast_food', cuisine: 'crepe' },
  'cryotherapy': null,
  'cuban': { amenity: 'restaurant', cuisine: 'cuban' },
  'culturalcenter': null,
  'cupcakes': null,
  'currencyexchange': null,
  'customcakes': null,
  'custommerchandise': null,
  'cyclingclass': null,
  'cypriot': { amenity: 'restaurant', cuisine: 'cypriot' },
  'czech': { amenity: 'restaurant', cuisine: 'czech' },
  'danceclub': null,
  'danceschool': null,
  'dancestudio': null,
  'dancewear': null,
  'danish': { amenity: 'restaurant', cuisine: 'danish' },
  'datarecovery': null,
  'dayspa': null,
  'dealer.usedvehicle': null,
  'delicatessen': null,
  'delicatessen.sandwiches': null,
  'dentalhygiene': null,
  'dentistry': null,
  'dentistry.cosmetic': null,
  'dentistry.general': null,
  'dentistry.pediatric': null,
  'departmentstore': null,
  'deptartmentstore': null,
  'dermatology': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'dermatology' },
  'desserts': null,
  'diagnosticimaging': null,
  'diagnosticservices': null,
  'dialysis': null,
  'dietician': null,
  'digitizingservices': null,
  'diner': { amenity: 'restaurant', cuisine: 'diner' },
  'dinnertheater': null,
  'discountstore': null,
  'distillery': null,
  'divebar': null,
  'diyfood': null,
  'dmv': null,
  'dominican': { amenity: 'restaurant', cuisine: 'dominican' },
  'donair': { amenity: 'restaurant', cuisine: 'donair' },
  'donationcenter': null,
  'donuts': null,
  'doorsalesandinstallation': null,
  'drivingrange': null,
  'drivingschool': null,
  'drycleaning': null,
  'drycleaninglaundry': null,
  'dumplings': { amenity: 'restaurant', cuisine: 'dumpling' },
  'dumpsterrental': null,
  'dutyfree': null,
  'earnosethroat': null,
  'easterneuropean': null,
  'eatertainment': null,
  'editorialservices': null,
  'education': null,
  'educationservices': null,
  'egyptian': { amenity: 'restaurant', cuisine: 'egyptian' },
  'electricians': null,
  'electronicappliances': null,
  'electronicparts': null,
  'electronicsrepair': null,
  'elementaryschool': null,
  'embroiderycrochet': null,
  'emergencymedicine': null,
  'emissionstesting': null,
  'empanadas': { amenity: 'restaurant', cuisine: 'empanada' },
  'employmentagency': null,
  'endodontics': null,
  'engraving': null,
  'escapegame': null,
  'ethiopian': { amenity: 'restaurant', cuisine: 'ethiopian' },
  'ethnicgrocerystore': null,
  'european.modern': { amenity: 'restaurant', cuisine: 'european' },
  'eventplanning': null,
  'eventspace': null,
  'experiences': null,
  'eyelashes': null,
  'eyewear.opticians': null,
  'fabricstore': null,
  'fairground': null,
  'falafel': { amenity: 'restaurant', cuisine: 'falafel' },
  'familyfriendly': null,
  'familyfuncenter': null,
  'familymedicine': null,
  'familyplanning': null,
  'familyrestaurant': null,
  'farm': null,
  'farmersmarket': null,
  'fashion': null,
  'fashionaccessories': null,
  'fastfood': { amenity: 'fastfood' },
  'fencing': null,
  'fengshui': null,
  'ferry': null,
  'fieldofplay': null,
  'filipino': { amenity: 'restaurant', cuisine: 'filipino' },
  'financialservices': null,
  'fingerprinting': null,
  'firearmstrainingschool': null,
  'fish': { amenity: 'restaurant', cuisine: 'fish' },
  'fishandchips': { amenity: 'restaurant', cuisine: 'fish_and_chips' },
  'fitnessbootcamp': null,
  'fitnessequipment': null,
  'fitnessinstruction': null,
  'fixedbaseoperator': null,
  'flatbread': null,
  'flightinstructionschool': null,
  'floatspa': null,
  'flooringinstallationandrepair': null,
  'floraldesign': null,
  'florist': null,
  'florists': null,
  'flowers': null,
  'fondue': null,
  'foodcourt': null,
  'fooddelivery': null,
  'foodstand': null,
  'foodtruck': null,
  'formalwear': null,
  'formalwear.rental': null,
  'freiduria': null,
  'french': { amenity: 'restaurant', cuisine: 'french' },
  'french.alsatian': { amenity: 'restaurant', cuisine: 'french;alsatian' },
  'french.auvergnat': { amenity: 'restaurant', cuisine: 'french;auvergnat' },
  'french.baguette': { amenity: 'fast_food', cuisine: 'french;baguette' },
  'french.berrichon': { amenity: 'restaurant', cuisine: 'french;berrichon' },
  'french.bourguignon': { amenity: 'restaurant', cuisine: 'french;bourguignon' },
  'french.brasserie': { amenity: 'brewery', cuisine: 'french;brasserie' },
  'french.lyonnais': { amenity: 'restaurant', cuisine: 'french;lyonnais' },
  'french.nicois': { amenity: 'restaurant', cuisine: 'french;nicois' },
  'french.provencal': { amenity: 'restaurant', cuisine: 'french;provencal' },
  'friterie': { amenity: 'fast_food', cuisine: 'friture' },
  'frozenfoods': null,
  'fruitandvegetables': null,
  'fuelstation': null,
  'funeralservices': null,
  'furclothing': null,
  'furniture': { shop: 'furniture' },
  'furniture.rental': null,
  'furniturestore': { shop: 'furniture' },
  'gardening': null,
  'gastroenterology': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'gastroenterology' },
  'gastropubs': { amenity: 'restaurant', cuisine: 'gastropub' },
  'gelato': null,
  'georgian': { amenity: 'restaurant', cuisine: 'georgian' },
  'german': { amenity: 'restaurant', cuisine: 'german' },
  'german.baden': { amenity: 'restaurant', cuisine: 'german;baden' },
  'german.bavarian': { amenity: 'restaurant', cuisine: 'german;bavarian' },
  'german.currysausage': { amenity: 'restaurant', cuisine: 'german;currywurst' },
  'german.easterngerman': { amenity: 'restaurant', cuisine: 'german;eastern_german' },
  'german.fischbroetchen': { amenity: 'restaurant', cuisine: 'german;fischbroetchen' },
  'german.franconian': { amenity: 'restaurant', cuisine: 'german;franconian' },
  'german.hessian': { amenity: 'restaurant', cuisine: 'german;hessian' },
  'german.heuriger': { amenity: 'restaurant', cuisine: 'german;heuriger' },
  'german.northerngerman': { amenity: 'restaurant', cuisine: 'german;northern_german' },
  'german.palatine': { amenity: 'restaurant', cuisine: 'german;palatine' },
  'german.rhinelandian': { amenity: 'restaurant', cuisine: 'german;rhinelandian' },
  'german.swabian': { amenity: 'restaurant', cuisine: 'german;swabian' },
  'giblets': null,
  'giftshops': null,
  'glutenfree': null,
  'gokarting': null,
  'goldmerchants': null,
  'golf': null,
  'golf.instruction': null,
  'golfequipment': null,
  'golfshop': null,
  'gourmetfood': null,
  'gourmetmarket': null,
  'graphicaldesign': null,
  'greek': { amenity: 'restaurant', cuisine: 'greek' },
  'grillingequipment': null,
  'grocery': null,
  'grocery.asian': null,
  'grocery.chinese': null,
  'grocery.indian': null,
  'grocery.japanese': null,
  'grocery.korean': null,
  'grocery.persian': null,
  'grocerystore': null,
  'guitarstore': null,
  'gunrange': null,
  'gunsandammo': null,
  'gym': null,
  'gymnastics': null,
  'hairblowout': null,
  'haircutsstyling': null,
  'haircutsstyling.mens': null,
  'hairextensions': null,
  'hairloss': null,
  'hairremoval': null,
  'hairremoval.laser': null,
  'hairremoval.threading': null,
  'hairremoval.waxing': null,
  'hairstylist': null,
  'haitian': { amenity: 'restaurant', cuisine: 'haitian' },
  'halal': null,
  'hardware': null,
  'hats': null,
  'hauntedhouse': null,
  'hawaiian': { amenity: 'restaurant', cuisine: 'hawaiian' },
  'headshop': null,
  'healthcare': null,
  'healthcarecenter': null,
  'healthyfoods': null,
  'hearingaidproviders': null,
  'hearingaids': null,
  'hennaartist': null,
  'herbalmedicine': { healthcare: 'alternative', 'healthcare:speciality': 'herbalism', 'fixme': 'is this actually a herbal shop?'},
  'herbsandspices': null,
  'highschool': null,
  'himalayan': { amenity: 'restaurant', cuisine: 'himalayan' },
  'hobbyshop': null,
  'holidaydecorations': null,
  'homeandgarden': null,
  'homeappliancerepair': null,
  'homeautomation': null,
  'homecleaning': null,
  'homedecor': null,
  'homedevelopers': null,
  'homegarden': null,
  'homehealthcare': null,
  'homeopathy': { healthcare: 'alternative', 'healthcare:speciality': 'homeopathy'},
  'hometheaterinstallation': null,
  'honey': null,
  'hongkong.cafe': null,
  'hookahbar': null,
  'horsequipment': null,
  'hospital': null,
  'hostel': null,
  'hotdogs': null,
  'hotel': null,
  'hotel.business': null,
  'hotel.capsule': null,
  'hotelbar': null,
  'hotpot': null,
  'hottubandpool': null,
  'housingcooperative': null,
  'hungarian': { amenity: 'restaurant', cuisine: 'hungarian' },
  'huntingfishingsupplies': null,
  'hvac': null,
  'hypermarket': null,
  'iberian': { amenity: 'restaurant', cuisine: 'iberian' },
  'icecream': null,
  'importedfood': null,
  'indian': { amenity: 'restaurant', cuisine: 'indian' },
  'indian.andhra': { amenity: 'restaurant', cuisine: 'indian;andhra' },
  'indian.assamese': { amenity: 'restaurant', cuisine: 'indian;assamese' },
  'indian.awadhi': { amenity: 'restaurant', cuisine: 'indian;awadhi' },
  'indian.bihari': { amenity: 'restaurant', cuisine: 'indian;bihari' },
  'indian.chettinad': { amenity: 'restaurant', cuisine: 'indian;chettinad' },
  'indian.goan': { amenity: 'restaurant', cuisine: 'indian;goon' },
  'indian.gujarat': { amenity: 'restaurant', cuisine: 'indian;gujarat' },
  'indian.hyderabadi': { amenity: 'restaurant', cuisine: 'indian;hyderabadi' },
  'indian.kerala': { amenity: 'restaurant', cuisine: 'indian;kerala' },
  'indian.konkan': { amenity: 'restaurant', cuisine: 'indian;konkan' },
  'indian.lucknowi': { amenity: 'restaurant', cuisine: 'indian;lucknowi' },
  'indian.maharashtrian': { amenity: 'restaurant', cuisine: 'indian;maharashtrian' },
  'indian.malwani': { amenity: 'restaurant', cuisine: 'indian;malwani' },
  'indian.mangalorean': { amenity: 'restaurant', cuisine: 'indian;mangalorean' },
  'indian.northindian': { amenity: 'restaurant', cuisine: 'indian;north_indian' },
  'indian.oriya': { amenity: 'restaurant', cuisine: 'indian;oriya' },
  'indian.rajasthani': { amenity: 'restaurant', cuisine: 'indian;rajasthani' },
  'indian.southindian': { amenity: 'restaurant', cuisine: 'indian;south_indian' },
  'indonesian': { amenity: 'restaurant', cuisine: 'indonesian' },
  'informationtechnology': null,
  'installmentloanservices': null,
  'insulationinstallation': null,
  'insurance': null,
  'insurance.auto': null,
  'insurance.health': null,
  'insurance.home': null,
  'insurance.life': null,
  'interiordesign': null,
  'internalmedicine': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'internal' },
  'internationalfood': null,
  'internetbooth': null,
  'internetcafe': null,
  'internetserviceprovider': null,
  'investmentbanking': null,
  'irish': { amenity: 'restaurant', cuisine: 'irish' },
  'irishpub': null,
  'israeli': { amenity: 'restaurant', cuisine: 'israeli' },
  'italian': { amenity: 'restaurant', cuisine: 'italian' },
  'italian.abruzzese': { amenity: 'restaurant', cuisine: 'italian;abruzzese' },
  'italian.altoatesine': { amenity: 'restaurant', cuisine: 'italian;altoatesine' },
  'italian.apulian': { amenity: 'restaurant', cuisine: 'italian;apulian' },
  'italian.calabrian': { amenity: 'restaurant', cuisine: 'italian;calabrian' },
  'italian.cucinacampana': { amenity: 'restaurant', cuisine: 'italian;cucinacampana' },
  'italian.diner': { amenity: 'restaurant', cuisine: 'italian;diner' },
  'italian.emilian': { amenity: 'restaurant', cuisine: 'italian;emilian' },
  'italian.friulan': { amenity: 'restaurant', cuisine: 'italian;friulan' },
  'italian.lumbard': { amenity: 'restaurant', cuisine: 'italian;lumbard' },
  'italian.napoletana': { amenity: 'restaurant', cuisine: 'italian;napoletana' },
  'italian.norcinerie': { amenity: 'restaurant', cuisine: 'italian;norcinerie' },
  'italian.piedmont': { amenity: 'restaurant', cuisine: 'italian;piedmont' },
  'italian.roman': { amenity: 'restaurant', cuisine: 'italian;roman' },
  'italian.sardinian': { amenity: 'restaurant', cuisine: 'italian;sardinian' },
  'italian.sicilian': { amenity: 'restaurant', cuisine: 'italian;sicilian' },
  'italian.tuscan': { amenity: 'restaurant', cuisine: 'italian;tuscan' },
  'italian.venetian': { amenity: 'restaurant', cuisine: 'italian;venetian' },
  'ivhydration': null,
  'izakaya': null,
  'japanese': { amenity: 'restaurant', cuisine: 'japanese' },
  'japanese.bento': { amenity: 'restaurant', cuisine: 'japanese;bento' },
  'japanese.blowfish': { amenity: 'restaurant', cuisine: 'japanese;blowfish' },
  'japanese.curry': { amenity: 'restaurant', cuisine: 'japanese;curry' },
  'japanese.donburi': { amenity: 'restaurant', cuisine: 'japanese;donburi' },
  'japanese.gyudon': { amenity: 'restaurant', cuisine: 'japanese;gyudon' },
  'japanese.handrolls': { amenity: 'restaurant', cuisine: 'japanese;handrolls' },
  'japanese.horumon': { amenity: 'restaurant', cuisine: 'japanese;horumon' },
  'japanese.kushikatsu': { amenity: 'restaurant', cuisine: 'japanese;kushikatsu' },
  'japanese.nikkei': { amenity: 'restaurant', cuisine: 'japanese;nikkei' },
  'japanese.oden': { amenity: 'restaurant', cuisine: 'japanese;oden' },
  'japanese.okonomiyaki': { amenity: 'restaurant', cuisine: 'japanese;okonomiyaki' },
  'japanese.onigiri': { amenity: 'restaurant', cuisine: 'japanese;onigiri' },
  'japanese.oyakodon': { amenity: 'restaurant', cuisine: 'japanese;oyakodon' },
  'japanese.ramen': { amenity: 'restaurant', cuisine: 'japanese;ramen' },
  'japanese.shabushabu': { amenity: 'restaurant', cuisine: 'japanese;shabushabu' },
  'japanese.soba': { amenity: 'restaurant', cuisine: 'japanese;soba' },
  'japanese.sukiyaki': { amenity: 'restaurant', cuisine: 'japanese;sukiyaki' },
  'japanese.takoyaki': { amenity: 'restaurant', cuisine: 'japanese;takoyaki' },
  'japanese.tempura': { amenity: 'restaurant', cuisine: 'japanese;tempura' },
  'japanese.teppanyaki': { amenity: 'restaurant', cuisine: 'japanese;teppanyaki' },
  'japanese.tonkatsu': { amenity: 'restaurant', cuisine: 'japanese;tonkatsu' },
  'japanese.udon': { amenity: 'restaurant', cuisine: 'japanese;udon' },
  'japanese.unagi': { amenity: 'restaurant', cuisine: 'japanese;unagi' },
  'japanese.westernjapanese': { amenity: 'restaurant', cuisine: 'japanese;western_japanese' },
  'japanese.yakiniku': { amenity: 'restaurant', cuisine: 'japanese;yakiniku' },
  'japanese.yakitori': { amenity: 'restaurant', cuisine: 'japanese;yakitori' },
  'japanesesweets': null,
  'jewelry': null,
  'jewelryrepair': null,
  'jewish': { amenity: 'restaurant', cuisine: 'jewish' },
  'juicebar': null,
  'kaiseki': { amenity: 'restaurant', cuisine: 'kaiseki' },
  'karaoke': null,
  'kashmiri': { amenity: 'restaurant', cuisine: 'kashmiri' },
  'kebab': { amenity: 'restaurant', cuisine: 'kebab' },
  'kidsactivities': null,
  'kimonos': null,
  'kindergarten': null,
  'kiosk': null,
  'kiosk.food': null,
  'kitchenandbath': null,
  'kitchenincubator': null,
  'knifesharpening': null,
  'knittingsupplies': null,
  'kopitiam': null,
  'korean': { amenity: 'restaurant', cuisine: 'korean' },
  'kosher': null,
  'kurdish': { amenity: 'restaurant', cuisine: 'kurdish' },
  'laboratorytesting': null,
  'landmark': null,
  'landscaping': null,
  'languageschool': null,
  'laotian': { amenity: 'restaurant', cuisine: 'laotian' },
  'lasereyesurgery': null,
  'lasertag': null,
  'latinamerican': null,
  'laundromat': null,
  'laundryservices': null,
  'lawyer': null,
  'lawyer.business': null,
  'lawyer.criminaldefense': null,
  'lawyer.divorce': null,
  'lawyer.estateplanning': null,
  'lawyer.immigration': null,
  'lawyer.litigation': null,
  'lawyer.personalinjury': null,
  'lawyer.realestate': null,
  'lawyer.tax': null,
  'lawyer.willtrustprobate': null,
  'lawyer.workerscomp': null,
  'leathergoods': null,
  'lebanese': { amenity: 'restaurant', cuisine: 'lebanese' },
  'legalservices': null,
  'library': null,
  'lifecoach': null,
  'lighting': null,
  'ligurian': { amenity: 'restaurant', cuisine: 'ligurian' },
  'limo': null,
  'linens': null,
  'lingerie': null,
  'livestocksales': null,
  'localservices': null,
  'locksmith': null,
  'lotterystand': null,
  'loungebar': null,
  'luggage': null,
  'luggagestorage': null,
  'macaron': null,
  'magicians': null,
  'mailboxcenter': null,
  'makeupartist': null,
  'malaysian': { amenity: 'restaurant', cuisine: 'malaysian' },
  'mamak': null,
  'manicurists': null,
  'marketing': null,
  'martialarts': null,
  'massageschool': null,
  'massagetherapist': null,
  'massagetherapy': null,
  'maternitywear': null,
  'mattresses': null,
  'mauritian': null,
  'meatballs': null,
  'medicalcenter': null,
  'medicalspa': null,
  'medicalsupplies': null,
  'mediterranean': null,
  'mexican': { amenity: 'restaurant', cuisine: 'mexican' },
  'mexican.easternmexican': { amenity: 'restaurant', cuisine: 'mexican;eastern_mexican' },
  'mexican.jaliscan': { amenity: 'restaurant', cuisine: 'mexican;jaliscan' },
  'mexican.modern': { amenity: 'restaurant', cuisine: 'mexican;modern' },
  'mexican.northernmexican': { amenity: 'restaurant', cuisine: 'mexican;northern_mexican' },
  'mexican.oaxacan': { amenity: 'restaurant', cuisine: 'mexican;oaxacan' },
  'mexican.pueblan': { amenity: 'restaurant', cuisine: 'mexican;pueblan' },
  'mexican.yucatan': { amenity: 'restaurant', cuisine: 'mexican;yucatan' },
  'middleeastern': { amenity: 'restaurant', cuisine: 'middle_eastern' },
  'militarybase': null,
  'milkbar': null,
  'milkshakes': null,
  'minigolf': null,
  'mobilephonerepair': null,
  'mobilephones': null,
  'moneytransferservices': null,
  'mongolian': { amenity: 'restaurant', cuisine: 'mongolian' },
  'moroccan': { amenity: 'restaurant', cuisine: 'moroccan' },
  'mortgagebroker': null,
  'motorcyclingclothing': null,
  'movierental.kiosk': null,
  'mughlai': null,
  'museum.art': null,
  'museum.children': null,
  'museum.history': null,
  'musicalinstruments': null,
  'musicalinstrumentservices': null,
  'musicvenue': null,
  'musicvideo': null,
  'naga': null,
  'nasilemak': null,
  'naturopathy': { healthcare: 'alternative', 'healthcare:speciality': 'naturopathy'},
  'nepalese': { amenity: 'restaurant', cuisine: 'nepalese' },
  'newspapersandmagazines': null,
  'newzealand': { amenity: 'restaurant', cuisine: 'newzealand' },
  'nicaraguan': { amenity: 'restaurant', cuisine: 'nicaraguan' },
  'nightfood': null,
  'nonprofit': null,
  'noodles': { amenity: 'restaurant', cuisine: 'noodles' },
  'northamerican.traditional': { amenity: 'restaurant', cuisine: 'north_american;traditional' },
  'norwegian': { amenity: 'restaurant', cuisine: 'norwegian' },
  'notarypublic': null,
  'nurseries.gardening': null,
  'nyonya': { amenity: 'restaurant', cuisine: 'nyonya' },
  'obgyn': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'gynaecology' },
  'observatory': null,
  'occupationaltherapy': null,
  'officebuilding': null,
  'officeequipmentandsupplies': null,
  'okinawan': { amenity: 'restaurant', cuisine: 'okinawan' },
  'oliveoil': null,
  'opensandwiches': null,
  'opera.ballet': null,
  'opthamalogy': null,
  'opticians': null,
  'optometry': null,
  'oralsurgery': null,
  'organicfood': null,
  'oriental': { amenity: 'restaurant', cuisine: 'oriental' },
  'orthodontics': null,
  'orthopedics': null,
  'orthotics': null,
  'osteopathy': { healthcare: 'alternative', 'healthcare:speciality': 'osteopathy'},
  'ottoman': null,
  'outdoorfurniture': null,
  'outdoorgear': null,
  'outletmall': null,
  'outletstore': null,
  'oxygenbar': null,
  'pachinko': null,
  'packagelocker': null,
  'packing': null,
  'packingsupplies': null,
  'paella': { amenity: 'restaurant', cuisine: 'paella' },
  'painmanagement': null,
  'paintandsip': null,
  'painting': null,
  'paintstores': null,
  'paintyourownpottery': null,
  'pakistani': { amenity: 'restaurant', cuisine: 'pakistani' },
  'parentingschool': null,
  'parking': null,
  'parks': null,
  'parma': { amenity: 'restaurant', cuisine: 'parma' },
  'parsi': { amenity: 'restaurant', cuisine: 'parsi' },
  'partycharacters': null,
  'partyequipment.rental': null,
  'partysupplies': null,
  'passportvisaservices': null,
  'pasta': null,
  'pathology': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'pathology' },
  'pawn': null,
  'paydayloan': null,
  'pediatrics': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'paediatrics' },
  'performingarts': null,
  'perfume': null,
  'periodontics': null,
  'permanentmakeup': null,
  'persian': { amenity: 'restaurant', cuisine: 'persian' },
  'personalcare': null,
  'personalshopper': null,
  'personaltrainer': null,
  'peruvian': { amenity: 'restaurant', cuisine: 'peruvian' },
  'pets': null,
  'pets.adoption': null,
  'pets.boarding': null,
  'pets.grooming': null,
  'pets.photography': null,
  'pets.sitting': null,
  'pets.training': null,
  'pets.transportation': null,
  'petstore': null,
  'petstore.fish': null,
  'petstore.reptile': null,
  'pharmacy': null,
  'pharmacystore': null,
  'phonechargingstation': null,
  'photobooth.rental': null,
  'photography': null,
  'photography.event': null,
  'photography.session': null,
  'photographyequipment': null,
  'photographystore': null,
  'physicaltherapy': null,
  'physician': { 'amenity': 'doctors', 'healthcare': 'doctor' },
  'piadina': null,
  'pianobar': null,
  'pianostore': null,
  'pictureframing': null,
  'pilates': null,
  'pita': null,
  'pizza': { amenity: 'restaurant' },
  'placeofworship': null,
  'placeofworship.church': null,
  'placeofworship.mosque': null,
  'placeofworship.synagogue': null,
  'placeofworship.unitarian': null,
  'planetarium': null,
  'plasticsurgery': null,
  'playcenter': null,
  'playground': null,
  'playsets': null,
  'plaza': null,
  'podiatrists': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'podiatry' },
  'podiatry': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'podiatry' },
  'poke': { amenity: 'restaurant', cuisine: 'poke' },
  'poledancingschool': null,
  'policestation': null,
  'policestation.koban': null,
  'polish': { amenity: 'restaurant', cuisine: 'polish' },
  'polish.pierogis': { amenity: 'restaurant', cuisine: 'polish;pierogi' },
  'poolcleaning': null,
  'poolhall': null,
  'pooltablesupplies': null,
  'popcorn': null,
  'popup': null,
  'popupshops': null,
  'portuguese': { amenity: 'restaurant', cuisine: 'portuguese' },
  'portuguese.alentejo': { amenity: 'restaurant', cuisine: 'portuguese;alentejo' },
  'portuguese.algarve': { amenity: 'restaurant', cuisine: 'portuguese;algarve' },
  'portuguese.azores': { amenity: 'restaurant', cuisine: 'portuguese;azores' },
  'portuguese.beira': { amenity: 'restaurant', cuisine: 'portuguese;beira' },
  'portuguese.fadohouse': { amenity: 'restaurant', cuisine: 'portuguese;fadohouse' },
  'portuguese.madeira': { amenity: 'restaurant', cuisine: 'portuguese;madeira' },
  'portuguese.minho': { amenity: 'restaurant', cuisine: 'portuguese;minho' },
  'portuguese.ribatejo': { amenity: 'restaurant', cuisine: 'portuguese;ribatejo' },
  'portuguese.trasosmontes': { amenity: 'restaurant', cuisine: 'portuguese;trasosmontes' },
  'postoffice': null,
  'postoffice.authorizedagent': null,
  'potatoes': null,
  'poutineries': null,
  'prenatal': null,
  'preschool': null,
  'pretzels': null,
  'preventivemedicine': null,
  'printmedia': null,
  'privateinvestigation': null,
  'privatejetcharter': null,
  'privateschool': null,
  'privateshuttlebus': null,
  'professionalservices': null,
  'professionalsportsteam': null,
  'propertymanagement': null,
  'psychiatrists': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'psychiatry' },
  'psychiatry': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'psychiatry' },
  'psychic': null,
  'psychology': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'psychology' },
  'pub': {
    amenity: 'pub'
  },
  'publicart': null,
  'publiclibrary': null,
  'publicservices.government': null,
  'publictransport': null,
  'puertorican': { amenity: 'restaurant', cuisine: 'puertorican' },
  'pulmonology': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'pulmonology' },
  'punjabi': { amenity: 'restaurant', cuisine: 'punjabi' },
  'racetrack': null,
  'radiology': { 'amenity': 'clinic', 'healthcare': 'clinic', 'healthcare:specialty': 'radiology' },
  'radiostation': null,
  'rawfood': null,
  'realestate.agents': null,
  'realestate.services': null,
  'realestateagents': null,
  'realestateagents.commercial': null,
  'realestateservices': null,
  'recordingstudio': null,
  'recreation': null,
  'recreationcenter': null,
  'recyclingcenter': null,
  'reflexology': { healthcare: 'alternative', 'healthcare:speciality': 'reflexology'},
  'religiousitems': null,
  'rental.videoandgame': null,
  'researchanddevelopment': null,
  'residentialapartments': null,
  'restaurant': { amenity: 'restaurant' },
  'retirementhome': null,
  'reunionnese': { amenity: 'restaurant', cuisine: 'reunionnese' },
  'reupholstery': null,
  'riceshop': null,
  'rideshare': null,
  'robatayaki': null,
  'rockclimbing': null,
  'rodizio': null,
  'romanian': { amenity: 'restaurant', cuisine: 'romanian' },
  'roofing': null,
  'rotisseriechicken': null,
  'rugs': null,
  'russian': { amenity: 'restaurant', cuisine: 'russian' },
  'sakebar': null,
  'salad': { amenity: 'restaurant', cuisine: 'salad' },
  'salvadoran': { amenity: 'restaurant', cuisine: 'salvadoran' },
  'sandwiches': null,
  'sauna': null,
  'scandinavian': { amenity: 'restaurant', cuisine: 'scandinavian' },
  'scandinaviandesign': null,
  'school': { amenity: 'school' },
  'scottish': { amenity: 'restaurant', cuisine: 'scottish' },
  'screenprinting': null,
  'screenprinting.tshirt': null,
  'seafood': null,
  'seafoodmarket': null,
  'securitysystems': null,
  'selfstorage': null,
  'senegalese': { amenity: 'restaurant', cuisine: 'senegalese' },
  'seniorcenter': null,
  'serbianandcroatian': { amenity: 'restaurant', cuisine: 'serbian;croatian' },
  'sewingalterations': null,
  'sharedofficespace': null,
  'shavedice': null,
  'shavedsnow': null,
  'shippingcenters': null,
  'shippingdropbox': null,
  'shoerepair': null,
  'shoes': { shop: 'shoes'},
  'shoeshine': null,
  'shoestore': { shop: 'shoes' },
  'shopping': { shop: 'supermarket' },
  'shoppingpassage': null,
  'shutterinstallation': null,
  'signature': null,
  'signmaking': null,
  'silentdisco': null,
  'singaporean': { amenity: 'restaurant', cuisine: 'singaporean' },
  'skatepark': null,
  'skatingequipment': null,
  'skatingrink': null,
  'skiequipment': null,
  'skincare': null,
  'skydiving': null,
  'sleepwear': null,
  'slovakian': { amenity: 'restaurant', cuisine: 'slovakian' },
  'soccer': null,
  'socialclub': null,
  'socialservices': null,
  'softwaredevelopment': null,
  'solarinstallation': null,
  'sommeliers': null,
  'soulfood': { amenity: 'restaurant', cuisine: 'soulfood' },
  'soup': { amenity: 'restaurant', cuisine: 'soup' },
  'southafrican': { amenity: 'restaurant', cuisine: 'south_african' },
  'southernunitedstates': { amenity: 'restaurant', cuisine: 'american;southern' },
  'southwestunitedstates': { amenity: 'restaurant', cuisine: 'american;southwestern' },
  'souvenirs': { shop: 'gift' },
  'spanish': { amenity: 'restaurant', cuisine: 'spanish' },
  'spanish.andalusian': { amenity: 'restaurant', cuisine: 'spanish;andalusian' },
  'spanish.basque': { amenity: 'restaurant', cuisine: 'spanish;basque' },
  'spanish.catalan': { amenity: 'restaurant', cuisine: 'spanish;catalan' },
  'spanish.galician': { amenity: 'restaurant', cuisine: 'spanish;galician' },
  'specialtyfood': null,
  'specialtyschool': null,
  'spinclass': null,
  'spiritualproducts': null,
  'sportinggoods': null,
  'sportsbar': null,
  'sportsclub': null,
  'sportsequipment.rental': null,
  'sportsgoods': null,
  'sportsmedicine': null,
  'sportsschool': null,
  'sportswear': null,
  'srilankan': { amenity: 'restaurant', cuisine: 'srilankan' },
  'stationery': null,
  'steak': { amenity: 'restaurant', cuisine: 'steak' },
  'stockings': null,
  'streetvendor': null,
  'structuralengineers': null,
  'subwaystation': null,
  'supermarket': { shop: 'supermarket' },
  'supperclub': null,
  'surfacerefinishing': null,
  'surfing': null,
  'surfingequipment': null,
  'surgeon': null,
  'sushi': { amenity: 'restaurant' },
  'swedish': { amenity: 'restaurant', cuisine: 'swedish' },
  'swedish.traditional': { amenity: 'restaurant', cuisine: 'swedish;traditional' },
  'swimminginstruction': null,
  'swimmingpool': null,
  'swimwear': null,
  'swiss': { amenity: 'restaurant', cuisine: 'swiss' },
  'syrian': { amenity: 'restaurant', cuisine: 'syrian' },
  'taberna': { amenity: 'pub' },
  'tabletopgames': { shop: 'games'  },
  'tableware': { shop: 'tableware' },
  'tacos': { amenity: 'fast_food', cuisine: 'mexican;tacos' },
  'taiwanese': { amenity: 'restaurant', cuisine: 'taiwanese' },
  'taiyaki': { amenity: 'fast_food', cuisine: 'japanese;taiyaki' },
  'talentagencies': null,
  'tamales': { amenity: 'restaurant', cuisine: 'tamale' },
  'tanningbeds': { leisure: 'tanning_salon' },
  'tanningservices': { leisure: 'tanning_salon' },
  'tapas': { amenity: 'restaurant', cuisine: 'tapas' },
  'tapas.smallplate': { amenity: 'restaurant', cuisine: 'tapas' },
  'tattoo': { shop: 'tattoo' },
  'tattoo.removal': null,
  'taxi': { amenity: 'taxi' },
  'taxistand': { amenity: 'taxi' },
  'taxoffice': { office: 'tax_advisor' },
  'taxservices': { office: 'tax_advisor' },
  'tea': { shop: 'tea' },
  'teachersupplies': null,
  'teambuilding': null,
  'teethwhitening': null,
  'telecommunications': null,
  'televisionserviceproviders': null,
  'televisionstation': null,
  'tennis.instruction': null,
  'terminal': null,
  'terminal.bus': null,
  'testpreparationschool': null,
  'texmex': { amenity: 'restaurant', cuisine: 'tex-mex' },
  'thai': { amenity: 'restaurant', cuisine: 'thai' },
  'theater.drivein': { amenity: 'cinema', 'drive_in': 'yes' },
  'theater.movie': { amenity: 'cinema' },
  'themedcafe': null,
  'thriftstore': null,
  'tibetan': { amenity: 'restaurant', cuisine: 'tibetan' },
  'tickets': null,
  'tikibar': { amenity: 'bar', bar: 'tiki'},
  'titleloan': null,
  'tobaccoshop': { shop: 'tobacco' },
  'tofu': { amenity: 'restaurant', cuisine: 'tofu' },
  'touristattraction': null,
  'tours': { office: 'guide' },
  'tours.boat': null,
  'tours.bus': null,
  'tours.scooter': null,
  'tours.walking': null,
  'towncarservice': null,
  'toys': { shop: 'toys' },
  'toystore': { shop: 'toys' },
  'traditionalchinesemedicine': { healthcare: 'alternative', 'healthcare:speciality': 'traditional_chinese_medicine'},
  'trainserviceprovider': null,
  'trainstation': null,
  'trampolining': null,
  'transitlounge': null,
  'translationservices': null,
  'transportationservices': null,
  'trattoria': { amenity: 'restaurant', cuisine: 'italian;trattoria' },
  'travelagent': null,
  'travelservices': null,
  'trinidadian': { amenity: 'restaurant', cuisine: 'italian;trinidadian',
  'trophyshops': { shop: 'trophy' },
  'truckrental': { industrial: 'mobile_equipment', 'truck:rental': 'yes' },
  'tuina': { healthcare: 'alternative', 'healthcare:specialty': 'tuina' },
  'turkish': { amenity: 'restaurant', cuisine: 'turkish' },
  'turkish.cheekufta': { amenity: 'restaurant', cuisine: 'turkish;cheekufta' },
  'turkish.gozleme': { amenity: 'restaurant', cuisine: 'turkish;gozleme' },
  'turkish.homemadefood': { amenity: 'restaurant', cuisine: 'turkish' },
  'turkish.lahmacun': { amenity: 'restaurant', cuisine: 'turkish;lahmacun' },
  'turkish.ravioli': { amenity: 'restaurant', cuisine: 'turkish;ravioli' },
  'tutoring': { office: 'tutoring' },
  'ukrainian': { amenity: 'restaurant', cuisine: 'ukrainian' },
  'uniforms': { shop: 'clothes', clothes: 'uniforms'},
  'urgentcare': { amenity: 'clinic', healthcare: 'clinic', 'healthcare:specialty': 'urgent'},
  'usedbooks': { shop: 'books', 'second_hand': 'only' },
  'utilities': null,
  'uzbek': { amenity: 'restaurant', cuisine: 'uzbek' },
  'vacationhome': null,
  'vacationhome.agent': null,
  'valetservices': null,
  'vapeshops': null,
  'vascularmedicine': null,
  'vegan': { amenity: 'restaurant', cuisine: 'vegan' },
  'vegetarian': { amenity: 'restaurant', cuisine: 'vegetarian' },
  'vendingmachine': { amenity: 'vending_machine' },
  'vendingmachine.beverage': { amenity: 'vending_machine', 'vending': 'drinks' },
  'venezuelan': { amenity: 'restaurant', cuisine: 'venezuelan' },
  'venison': { amenity: 'restaurant', cuisine: 'venison' },
  'veteransorganization': { amenity: 'social_centre', club: 'veterans', 'social_centre:for': 'veterans' },
  'veterinarian': { amenity: 'veterinary' },
  'videofilmproduction': null,
  'videogamesandconsoles': null,
  'vietnamese': { amenity: 'restaurant', cuisine: 'vietnamese' },
  'vintageclothing': null,
  'vinylrecords': null,
  'virtualreality': null,
  'visitorcenter': null,
  'vitaminssupplements': null,
  'vocalcoach': null,
  'vocationalschool': null,
  'waffles': null,
  'walkinclinic': null,
  'warehouse': null,
  'watches': null,
  'watchrepair': null,
  'waterpark': null,
  'waterpurification': null,
  'webdesign': null,
  'weddingchappel': null,
  'weddingplanning': null,
  'weightloss': null,
  'welsh': { amenity: 'restaurant', cuisine: 'welsh' },
  'whiskeybar': null,
  'wholesalemerchant': null,
  'wholesaler': null,
  'wigs': null,
  'windowinstallation': null,
  'winebar': null,
  'winery': null,
  'winetasting': null,
  'wok': { amenity: 'restaurant', cuisine: 'wok' },
  'wraps': { amenity: 'fast_food', cuisine: 'wrap' },
  'yoga': null,
  'youthclub': null,
  'yugoslav': { amenity: 'restaurant', cuisine: 'yugoslav' },
};

const amenitiesCategoryToOsm = {
  'amphitheater': null,
  'animalreliefarea': null,
  'arrivalgate': null,
  'atm': { amenity: 'atm' },
  'babychanging': null,
  'baggagecarousel': null,
  'baggagecarousel.intl': null,
  'baggagecarts': null,
  'baggageclaim': null,
  'baggageclaim.oversize': null,
  'baggagerecheck': null,
  'baggagestorage': null,
  'boardinggate': null,
  'boardinggate.aircraft': null,
  'boardinggate.bus': null,
  'boardinggate.ferry': null,
  'boardinggate.train': null,
  'bus': null,
  'bus.muni': null,
  'bus.national': null,
  'businesscenter': null,
  'cabin': null,
  'caregiver': null,
  'carrental': null,
  'cashier': null,
  'changemachine': null,
  'checkin': null,
  'checkin.desk': null,
  'checkin.desk.oversizebaggage': null,
  'checkin.desk.transfer': null,
  'checkin.selfservice': null,
  'childplayarea': null,
  'coinlocker': null,
  'copymachine': null,
  'defibrillator': { emergency: 'defibrillator' },
  'drinkingfountain': null,
  'eatingdrinking': null,
  'elevator': null,
  'emergencyshelter': null,
  'entry': null,
  'escalator': null,
  'exhibit': null,
  'faregate': null,
  'faregate.oversized': null,
  'fieldofplay': null,
  'fieldofplay.americanfootball': null,
  'fieldofplay.baseball': null,
  'fieldofplay.basketball': null,
  'fieldofplay.fieldhockey': null,
  'fieldofplay.icehockey': null,
  'fieldofplay.rugby': null,
  'fieldofplay.soccer': null,
  'fieldofplay.softball': null,
  'fieldofplay.tennis': null,
  'fieldofplay.trackfield': null,
  'fieldofplay.volleyball': null,
  'firealarmpullstation': null,
  'fireextinguisher': null,
  'firstaid': null,
  'fittingroom': null,
  'foodservice': null,
  'gatearea': null,
  'groundtransportation': null,
  'guestservices': null,
  'handsanitizerstation': null,
  'healthscreening': null,
  'hoteling': null,
  'immigration': null,
  'information': { tourism: 'information' },
  'information.bid': { tourism: 'information' },
  'information.carrental': { tourism: 'information' },
  'information.hotel': { tourism: 'information' },
  'information.mufid': { tourism: 'information' },
  'information.mufid.arrivals': { tourism: 'information' },
  'information.mufid.departures': { tourism: 'information' },
  'information.transit': { tourism: 'information' },
  'landmark': null,
  'library': null,
  'limo': null,
  'lostandfound': null,
  'mailbox': null,
  'meditation': null,
  'meetingpoint': null,
  'mobilityrescue': null,
  'mothersroom': null,
  'movingwalkway': null,
  'paidarea': null,
  'parkandride': null,
  'parking': null,
  'parking.bicycle': null,
  'parking.compact': null,
  'parking.ev': null,
  'parking.longterm': null,
  'parking.motorcycle': null,
  'parking.shortterm': null,
  'parking.waitingarea': null,
  'payphone': null,
  'pedestriancrossing': null,
  'peoplemover': null,
  'phone': { amenity: 'telephone' },
  'phone.emergency': null,
  'photobooth': null,
  'platform': null,
  'police': null,
  'powerchargingstation': null,
  'prayerroom': null,
  'prayerroom.buddhism': null,
  'prayerroom.christianity': null,
  'prayerroom.hinduism': null,
  'prayerroom.islam': null,
  'prayerroom.islam.female': null,
  'prayerroom.islam.male': null,
  'prayerroom.judaism': null,
  'prayerroom.shintoism': null,
  'prayerroom.sikh': null,
  'prayerroom.taoic': null,
  'privatelounge': null,
  'productreturn': null,
  'rail.muni': null,
  'rail.national': null,
  'ramp': null,
  'reception.desk': null,
  'recreation': null,
  'restroom': { amenity: 'toilets' },
  'restroom.family': { amenity: 'toilets' },
  'restroom.female': { amenity: 'toilets' },
  'restroom.female.wheelchair': { amenity: 'toilets', wheelchair: 'yes' },
  'restroom.male': { amenity: 'toilets' },
  'restroom.male.wheelchair': { amenity: 'toilets', wheelchair: 'yes' },
  'restroom.transgender': { amenity: 'toilets' },
  'restroom.transgender.wheelchair': { amenity: 'toilets', wheelchair: 'yes' },
  'restroom.unisex': { amenity: 'toilets' },
  'restroom.unisex.wheelchair': { amenity: 'toilets', wheelchair: 'yes' },
  'restroom.wheelchair': { amenity: 'toilets', wheelchair: 'yes' },
  'rideshare': null,
  'seat': null,
  'seating': null,
  'security': null,
  'security.checkpoint': null,
  'security.inspection': null,
  'service': null,
  'shower': null,
  'shuttle': null,
  'sleepbox': null,
  'smokingarea': null,
  'stairs': null,
  'storage': null,
  'strollerrental': null,
  'studentadmissions': null,
  'studentservices': null,
  'swimmingpool': null,
  'swimmingpool.children': null,
  'swimmingpool.family': null,
  'taxi': null,
  'ticketing': null,
  'ticketing.airline': null,
  'ticketing.bus': null,
  'ticketing.bus.muni': null,
  'ticketing.bus.national': null,
  'ticketing.rail': null,
  'ticketing.rail.muni': null,
  'ticketing.rail.national': null,
  'ticketing.shuttle': null,
  'traintrack': null,
  'transit': null,
  'unspecified': null,
  'valet': null,
  'vendingmachine': { amenity: 'vending_machine' },
  'vendingmachine.trainticket': { amenity: 'vending_machine', vending: 'public_transport_tickets' },
  'wheelchairassist': null,
  'wifi': null,
  'yoga': null,
};


export function unitCategoryToClass(category) {
  return unitCategoryToOsm[category] ? unitCategoryToOsm[category] : 'room';
}

export function unitFeatureToAccess(feature) {
  if (['employeesonly', 'restricted'].includes(feature.properties.restriction)
     || feature.properties.category === 'nonpublic') {
    return 'no';
  }
  return 'yes';
};

export function collectUnitIdsWithPoi(anchors, occupants, amenities) {
  const unitIdOccupants = occupants.filter((feature) => {
    return occupantCategoryToOsm[feature.properties.category];
  }).map((feature, index) => {
    return anchors.find((anchor) => anchor.id === feature.properties.anchor_id).properties.unit_id;
  });
  const unitIdAmenities = amenities.filter((feature) => {
    return amenitiesCategoryToOsm[feature.properties.category];
  }).flatMap((feature, index) => {
    return feature.properties.unit_ids;
  });
  return uniq(unitIdOccupants.concat(unitIdAmenities));
}

export function transformOccupantFeatures(units, anchors, occupants, levelsById) {
  return occupants.filter((feature) => {
    return occupantCategoryToOsm[feature.properties.category];
  }).map((feature, index) => {
    const anchor = anchors.find((anchor) => anchor.id === feature.properties.anchor_id);
    const unit = units.find((unit) => unit.id === anchor.properties.unit_id);
    const mapping = occupantCategoryToOsm[feature.properties.category];
    const newFeature = {
      geometry: anchor.geometry,
      properties: {
        id: `poi_${index}`,
        ...mapping,
        'name': feature.properties.name.en,
        'name:latin': feature.properties.name.en,
        level: levelsById[unit.properties.level_id],
        opening_hours: feature.properties.hours,
        website: feature.properties.website,
        phone: feature.properties.phone,
      }
    };
    const [classe, subclass] = poiClassAndSubclass(newFeature);
    return {
      ...newFeature,
      properties: {
        ...newFeature.properties,
        class: classe,
        subclass
      }
    };
  });
}

export function transformOpeningFeatures(openings, levelsById) {
  return openings.map((feature, index) => {
    const featureCenter = centerOfMass(feature);
    return {
      ...feature,
      ...featureCenter,
      properties: {
        id: `poi_door_${index}`,
        door: 'yes',
        class: 'entrance',
        subclass: 'door',
        level: levelsById[feature.properties.level_id]
      }
    };
  });
}

export function transformAmenityFeatures(units, amenities, levelsById) {
  return amenities.filter((feature) => {
    return amenitiesCategoryToOsm[feature.properties.category];
  }).map((feature, index) => {
    const unit = units.find((unit) => feature.properties.unit_ids.includes(unit.id));
    const mapping = amenitiesCategoryToOsm[feature.properties.category];
    const newFeature = {
      ...feature,
      properties: {
        id: `poi_amenity_${index}`,
        ...mapping,
        'name': feature.properties.name?.en,
        'name:latin': feature.properties?.name?.en,
        level: levelsById[unit.properties.level_id],
        opening_hours: feature.properties.hours,
        website: feature.properties.website,
        phone: feature.properties.phone,
      }
    };
    const [classe, subclass] = poiClassAndSubclass(newFeature);
    return {
      ...newFeature,
      properties: {
        ...newFeature.properties,
        class: classe,
        subclass
      }
    };
  });
}

export function transformAreaFeatures(units, unitIdsWithPoi, levelsById) {
  return units.map((feature) => {
    return {
      ...feature,
      properties: {
        ...feature.properties,
        class: unitCategoryToClass(feature.properties.category),
        is_poi: unitIdsWithPoi.includes(feature.id),
        access: unitFeatureToAccess(feature),
        level: levelsById[feature.properties.level_id]
      }
    };
  });
}

async function readFileJSONFromZip(zip, filename) {
  return JSON.parse(await zip.file(filename).async('string'));
}

export async function transformIMDFFile(file) {
  const zip = await JSZip.loadAsync(file);
  const levels = await readFileJSONFromZip(zip, 'level.geojson');
  const units = await readFileJSONFromZip(zip, 'unit.geojson');
  const occupants = await readFileJSONFromZip(zip, 'occupant.geojson');
  const anchors = await readFileJSONFromZip(zip, 'anchor.geojson');
  const openings = await readFileJSONFromZip(zip, 'opening.geojson');
  const amenities = await readFileJSONFromZip(zip, 'amenity.geojson');
  const levelsById = levels.features.reduce((memo, level) => {
    memo[level.id] = level.properties.short_name.en;
    return memo;
  }, {});
  const unitIdsWithPoi = collectUnitIdsWithPoi(anchors.features, occupants.features, amenities.features);
  return {
    area: {
      type: 'FeatureCollection',
      features: transformAreaFeatures(units.features, unitIdsWithPoi, levelsById)
    },
    poi: {
      type: 'FeatureCollection',
      features: [
        ...transformOccupantFeatures(units.features, anchors.features, occupants.features, levelsById),
        ...transformAmenityFeatures(units.features, amenities.features, levelsById),
        ...transformOpeningFeatures(openings.features, levelsById),
      ]
    }
  };
}
